inherits = "catppuccin_mocha"

"ui.statusline.separator" = { fg = "surface1" }

"ui.bufferline" = { fg = "subtext0", bg = "surface0"}
"ui.bufferline.active" = { fg = "text", bg = "base", modifiers = [ "bold" ] }
"ui.bufferline.background" = { bg = "surface0" }

"variable.parameter" = { fg = "maroon" }
"keyword.control.conditional" = { fg = "mauve" }
"namespace" = { fg = "blue" }
