[character]
error_symbol = "✖ ❯"

[git_status]
ahead = "+"
behind = "-"
diverged = "±"
untracked = "…"
stashed = "\\$"
modified = "*"
staged = "~"
conflicted = "≠"

[package]
display_private = true

[nodejs]
disabled = true

[ruby]
disabled = true

[php]
disabled = true

[golang]
disabled = true

[kubernetes]
disabled = true

[conda]
disabled = true

[dotnet]
disabled = true

[env_var]
disabled = true

[hg_branch]
disabled = true

[memory_usage]
disabled = true

[java]
disabled = true

[terraform]
disabled = true

[haskell]
disabled = true

[buf]
disabled = true

[nix_shell]
disabled = true

[elixir]
disabled = true

[singularity]
disabled = true

[elm]
disabled = true

[crystal]
disabled = true

[docker_context]
disabled = true

[julia]
disabled = true

[erlang]
disabled = true

[ocaml]
disabled = true

[nim]
disabled = true

[purescript]
disabled = true

[zig]
disabled = true

[swift]
disabled = true

[perl]
disabled = true

[helm]
disabled = true

[dart]
disabled = true

[cmake]
disabled = true

[lua]
disabled = true

[openstack]
disabled = true

#[meson]
#disabled = true

[kotlin]
disabled = true

[vagrant]
disabled = true

[deno]
disabled = true

[vlang]
disabled = true

[rlang]
disabled = true

[cobol]
disabled = true

[pulumi]
disabled = true

[sudo]
disabled = false

[daml]
disabled = true

[raku]
disabled = false

[meson]
disabled = false

