[character]
error_symbol = "✖ ❯"
use_symbol_for_status = true

[git_status]
ahead = "+"
behind = "-"
diverged = "±"
untracked = "…"
stashed = "$"
modified = "*"
staged = "~"
conflicted = "≠"

[package]
display_private = true

[nodejs]
disabled = true

[ruby]
disabled = true

[php]
disabled = true

[golang]
disabled = true

[kubernetes]
disabled = true

[battery]
disabled = true

[conda]
disabled = true

[dotnet]
disabled = true

[env_var]
disabled = true

[hg_branch]
disabled = true

[memory_usage]
disabled = true

[java]
disabled = true

[terraform]
disabled = true

[haskell]
disabled = true

[nix_shell]
disabled = true

[elixir]
disabled = true

[singularity]
disabled = true

[elm]
disabled = true

[crystal]
disabled = true

[docker_context]
disabled = true

[julia]
disabled = true

[erlang]
disabled = true

[ocaml]
disabled = True

[nim]
disabled = True

[purescript]
disabled = True

[zig]
disabled = True

