[character]
error_symbol = "✖ ❯"

[git_state]
disabled = false

[git_status]
ahead = "+"
behind = "-"
diverged = "±"
untracked = "…"
stashed = "\\$"
modified = "*"
staged = "~"
conflicted = "≠"

[package]
display_private = true

[rust]
disabled = false

[nodejs]
disabled = false
symbol = "⬢ "

[deno]
disabled = false

[direnv]
disabled = false

[nix_shell]
disabled = false

[golang]
disabled = true

[kubernetes]
disabled = true

[ruby]
disabled = true

[php]
disabled = true

[conda]
disabled = true

[dotnet]
disabled = true

[env_var]
disabled = true

[hg_branch]
disabled = true

[memory_usage]
disabled = true

[java]
disabled = true

[terraform]
disabled = true

[haskell]
disabled = true

[buf]
disabled = true

[elixir]
disabled = true

[singularity]
disabled = true

[elm]
disabled = true

[crystal]
disabled = true

[docker_context]
disabled = true

[julia]
disabled = true

[erlang]
disabled = true

[ocaml]
disabled = true

[nim]
disabled = true

[purescript]
disabled = true

[zig]
disabled = true

[swift]
disabled = true

[perl]
disabled = true

[helm]
disabled = true

[dart]
disabled = true

[cmake]
disabled = true

[lua]
disabled = true

[openstack]
disabled = true

[kotlin]
disabled = true

[vagrant]
disabled = true

[vlang]
disabled = true

[rlang]
disabled = true

[cobol]
disabled = true

[pulumi]
disabled = true

[sudo]
disabled = false

[daml]
disabled = true

[raku]
disabled = true

[meson]
disabled = true

[pijul_channel]
disabled = true

[fennel]
disabled = true

[fossil_branch]
disabled = true

[gradle]
disabled = true

[haxe]
disabled = true

[os]
disabled = true

[guix_shell]
disabled = true

[solidity]
disabled = true

[typst]
disabled = true

[fossil_metrics]
disabled = true

[quarto]
disabled = true
