[[keyboard.bindings]]
action = "None"
key = "Q"
mods = "Control"

[terminal.shell]
program = "/home/mandx/.cargo/bin/zellij"
# args = ["arg1", "arg2"]

[window]
decorations = "none"

[font]
size = 11.5
normal = { family = "Ubuntu Mono" }
# builtin_box_drawing = false
