theme = "mandx"

[editor]
bufferline = "always"
cursorline = true
#line-number = "relative"
true-color = true
preview-completion-insert = false
completion-trigger-len = 1
completion-replace = false
color-modes = true
popup-border = "popup"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "▏"
skip-level = 1
render = true

[editor.lsp]
# Show LSP messages in the status line
display-messages = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
separator = "┋"
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator", "separator", "file-type", "diagnostics", "separator"]
center = ["version-control"]
right = ["separator", "register", "separator", "file-encoding", "separator", "selections", "position", "primary-selection-length"]

[keys.normal]
"tab" = ["indent"]
"S-tab" = ["unindent"]
"backspace" = ["move_char_left", "delete_selection_noyank"]
"end" = "insert_at_line_end"
"ret" = "open_below"
"esc" = ["collapse_selection", "keep_primary_selection"]
"G" = "goto_last_line"
"X" = ["extend_line_up", "extend_to_line_bounds"]
"A-1" = "goto_previous_buffer"
"A-2" = "goto_next_buffer"
"A-w" = ":buffer-close"
"A-/" = "toggle_comments"
"#" = "toggle_comments"
"C-left" = "move_prev_word_start"
"C-right" = "move_next_word_start"
"C-up" = "goto_prev_paragraph"
"C-down" = "goto_next_paragraph"
"C-a" = "select_all"
"C-u" = "no_op"
"C-d" = ["search_selection", "select_mode"]
"W" = "extend_next_word_start"
"L" = "extend_to_line_end"
"H" = "extend_to_line_start"
"S-right" = "extend_char_right"
"S-left" = "extend_char_left"
"S-up" = "extend_visual_line_up"
"S-down" = "extend_visual_line_down"

[keys.normal.space]
"left" = "jump_view_left"
"right" = "jump_view_right"
"up" = "jump_view_up"
"down" = "jump_view_down"
"K" = "signature_help"

[keys.normal.space.e]
w = ":write"
f = ":format"
r = ":reload"
R = ":reload-all"

[keys.normal."A-backspace"]
o = ":config-open"
r = ":config-reload"
l = ":open ~/.config/helix/languages.toml"
t = ":open ~/.config/helix/themes/mandx.toml"

[keys.select]
"C-u" = "no_op"
"C-d" = ["search_selection", "extend_search_next"]
"A-1" = "goto_previous_buffer"
"A-2" = "goto_next_buffer"
"A-w" = ":buffer-close"
"A-/" = "toggle_comments"
"#" = "toggle_comments"

[keys.insert]
"tab" = ["indent"]
"S-tab" = ["unindent"]
"ins" = ["paste_before"]
"C-left" = ["move_prev_word_start", "collapse_selection"]
"C-right" = ["move_next_word_start", "collapse_selection"]
"C-up" = ["goto_prev_paragraph", "collapse_selection"]
"C-down" = ["goto_next_paragraph", "collapse_selection"]
"C-home" = ["goto_file_start"]
"C-end" = ["goto_file_end"]
