theme = "monokai_pro_spectrum"

[editor]
bufferline = "always"
cursorline = true
#line-number = "relative"
true-color = true
preview-completion-insert = false
completion-trigger-len = 1
completion-replace = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "▏"
skip-level = 1
render = true

[editor.lsp]
# Show LSP messages in the status line
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
right = ["diagnostics", "selections", "register", "position", "primary-selection-length", "file-encoding"]
center = ["version-control"]
separator = "»"

[keys.normal]
"A-," = "goto_previous_buffer"
"A-/" = "goto_next_buffer"
"A-w" = ":buffer-close"
"X" = ["extend_line_up", "extend_to_line_bounds"]
"end" = ["goto_line_end", "move_char_right"]
"esc" = ["collapse_selection", "keep_primary_selection"]

[keys.normal."A-backspace"]
r = ":config-reload"
o = ":config-open"
l = ":o ~/.config/helix/languages.toml"

[keys.normal.g]
l = ["goto_line_end", "move_char_right"]
