[language-server.eslint]
command = "/home/mandx/.config/helix/lsp-servers/node_modules/.bin/vscode-eslint-language-server"
args = [ "--stdio" ]

[language-server.eslint.config]
codeActionsOnSave = { mode = "all", "source.fixAll.eslint" = true }
format = { enable = true }
nodePath = ""
quiet = false
rulesCustomizations = []
run = "onType"
validate = "on"
experimental = {}
problems = { shortenToSingleLine = false }

[language-server.typescript-language-server]
command = "/home/mandx/.config/helix/lsp-servers/node_modules/.bin/typescript-language-server"
args = [ "--stdio" ]
config.documentFormatting = false

[[language]]
name = "typescript"
language-servers = [ "typescript-language-server", "eslint" ]

[[language]]
name = "javascript"
scope = "source.js"
injection-regex = "(js|javascript)"
language-id = "javascript"
file-types = ["js", "mjs", "cjs", "rules", "es6", "pac", "jakefile"]
shebangs = ["node"]
roots = []
comment-token = "//"
indent = { tab-width = 2, unit = "  " }
language-servers = [ "typescript-language-server", "eslint" ]
