[language-server.eslint]
command = "vscode-eslint-language-server"
args = [ "--stdio" ]

[language-server.eslint.config]
codeAction.disableRuleComment = {}
codeAction.showDocumentation = {}
codeActionsOnSave = { mode = "all", "source.fixAll.eslint" = true }
format = { enable = true }
nodePath = ""
quiet = false
rulesCustomizations = [
  { "rule" = "prettier/prettier", "severity" = "warn" },
  { "rule" = "@typescript-eslint/no-unused-vars", "severity" = "warn" },
]
run = "onType"
validate = "on"
experimental = {}
problems = { shortenToSingleLine = false }

[language-server.typescript-language-server]
config.documentFormatting = false

[language-server.deno-lsp]
command = "deno"
args = ["lsp"]
environment = { NO_COLOR = "1" }

[language-server.deno-lsp.config.deno]
enable = true
# Uncomment to enable completion of unstable features of Deno
# unstable = true
# Uncomment to cache dependencies on save
cacheOnSave = true
cache = true
lint = true
# Enable completion of function calls
suggest.completeFunctionCalls = false
# Enable completion of importing from registries
# suggest.imports = { hosts = { "https://deno.land" = true } }
deno.codeLens.implementations = true
deno.codeLens.references = true
deno.codeLens.referencesAllFunctions = true
javascript.inlayHints.parameterNames.enabled = true
typescript.inlayHints.parameterNames.enabled = true
javascript.inlayHints.prameterTypes.enabled = true
typescript.inlayHints.prameterTypes.enabled = true
javascript.inlayHints.variableTypes.enabled = true
typescript.inlayHints.variableTypes.enabled = true
javascript.inlayHints.propertyDeclarationTypes.enabled  = true
typescript.inlayHints.propertyDeclarationTypes.enabled  = true
javascript.inlayHints.functionLikeReturnTypes.enabled = true
typescript.inlayHints.functionLikeReturnTypes.enabled = true
javascript.inlayHints.enumMemberValues.enabled = true
typescript.inlayHints.enumMemberValues.enabled = true

[[language]]
name = "typescript"
language-servers = [ "typescript-language-server", "eslint" ]
formatter = { command = "prettier", args = [ "--parser", "typescript" ] }

[[language]]
name = "tsx"
language-servers = [ "typescript-language-server", "eslint" ]
formatter = { command = "prettier", args = [ "--parser", "typescript" ] }

[[language]]
name = "javascript"
language-servers = [ "typescript-language-server", "eslint" ]
formatter = { command = "prettier", args = [ "--parser", "typescript" ] }

[[language]]
name = "json"
auto-format = false
formatter = { command = "prettier", args = [ "--parser", "json" ] }

[language-server.rust-analyzer.config.cargo]
features = "all"
